# Generated by Django 5.1.2 on 2024-10-19 18:45
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес')),
                ('deals', models.IntegerField(verbose_name='Сделка')),
            ],
        ),
    ]
