# Generated by Django 5.1.2 on 2024-10-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='deals',
            field=models.IntegerField(null=True, verbose_name='Сделка'),
        ),
    ]
