# Generated by Django 5.1.2 on 2024-11-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0002_alter_contact_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deals',
        ),
        migrations.AddField(
            model_name='contact',
            name='deal_count',
            field=models.IntegerField(null=True, verbose_name='Количество сделок'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Описание')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='essence.contact', verbose_name='Контакт')),
            ],
        ),
    ]
