# Generated by Django 5.1.2 on 2024-11-23 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0003_remove_contact_deals_contact_deal_count_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='essence.contact', verbose_name='Контакт'),
        ),
    ]
